name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master


jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            json-schema-for-humans

      - name: generate Schema docs
        run: generate-schema-doc --config-file sasjsconfig-docs.yaml docs/sasjsconfig-schema.json docs/sasjsconfig.html

#      - name: generate Schema in markdown - removed as cannot deploy md files in mkdocs
#        run: generate-schema-doc --config template_name=md docs/sasjsconfig-schema.json sasjsconfig.md

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: cli.sasjs.io
